#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
[ "$(uname)" != "Darwin" ] && LINKFLAGS="-linkmode external -extldflags -static -s"
go build -tags "$TAGS" -ldflags "-X github.com/rancher/catalog-service/cmd.VERSION=$VERSION $LINKFLAGS" -o bin/rancher-catalog-service
