#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

ARCH=${ARCH:?"ARCH not set"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

mv bin/rancher-catalog-service{,-sqlite}
TAGS=nosqlite CGO_ENABLED=0 ./scripts/build

mkdir -p dist/artifacts
tar cvJf dist/artifacts/rancher-catalog-service${SUFFIX}.tar.xz -C ./bin .
