#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:?"ARCH not set"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/../package

mkdir -p dist/artifacts
tar cvJf dist/artifacts/$(basename $BIN)${SUFFIX}.tar.xz -C $(dirname $BIN) .
